### ISSUE TITLE
Add support to kirkstone (layer is compatible with honister)

### ISSUE THREAD

**Issue by roby2014** [rauc/meta-rauc-community#94]
Feature request: Add support to kirkstone

```
  meta-rauc-community:
    url: "https://github.com/rauc/meta-rauc-community.git"
    branch: master
    path: layers/meta-rauc-community
    layers:
      meta-rauc-tegra:
```

ERROR: Layer meta-rauc-tegra is not compatible with the core layer which only supports these series: kirkstone (layer is compatible with honister)

I see there is `kirkstone` branch, but, is it actively updated and dev on?
